### ISSUE TITLE
Miglioramento 1 - nell'inserimento di un utente, impedire trigger popup gestisci password di Chrome

### ISSUE THREAD

**Issue by MicheGit** [DeltaXswe/cc4d#102]
Nella sezione amministratore, quando crei un utente, gli inserisci la password e confermi la form, il buon vecchio chrome ti chiede se la vuoi gestire. Questo comportamento, secondo me, è fastidioso. Ho il sospetto che chrome non guarda solo se il nome del campo è "password", ma guarda anche il type. Una soluzione che avevo visto su internet, che vorrei evitare perché è bruttina, è di mettere il `type` del campo come testo normale (nell'html) e poi settare la visualizzazione a pallini `•••••` con il js. Alla fine si può sempre fare così, ma secondo me fare ricerche in altre direzioni ne vale la pena

**Comment by albertolazari** [comment]
Mettiamo in pausa, perché non sembra fattibile confacilità e non è un grosso problema. Si vedrà più avanti, eventualmente.

**Comment by albertolazari** [comment]
Non verrà risolto.
