### ISSUE TITLE
TS 1.4.1.1 - Password sbagliata non dà errore

### ISSUE THREAD

**Issue by riccardopavan** [DeltaXswe/cc4d#89]

**Comment by MicheGit** [comment]
Verificato

Resta la cosa del "magari ci mettiamo il popup rosso al posto della snackbar con scritto 'Credenziali non valide'"

**Comment by MicheGit** [comment]
Verificato

Resta la cosa del "magari ci mettiamo il popup rosso al posto della snackbar con scritto 'Credenziali non valide'"
