### ISSUE TITLE
RNO1 - Cambiare sistema di login

### ISSUE THREAD

**Issue by MicheGit** [DeltaXswe/cc4d#93]
Oltre alle cose in più elencate qui sotto, corrisponde a RDF1.1.3, RDF1.2, RDF2.1

Il sistema di login automatico dal token remember me lascia a desiderare. Gli obiettivi di questa issue sono:
1. **ottenere le informazioni dell'utente tramite un nuovo endpoint**: serve un endpoint che prende 0 parametri e, dato il token remember me o il token di sessione, restituisce { username: string ; administrator: boolean }. Se viene chiamato senza nessuno di questi due token, restituirà 401; 
2. **dismettere l'interceptor**: è difficile da manutenere e fa solo casini. Grazie a Giacomo non ne abbiamo più bisogno, se non per il redirect in caso di 401 sulla pagina di login. Al posto di questo funzionamento discutibile, sposteremo il redirect al logout nelle guardie, più consono agli standard di angular.

Ricordo che, in questa maniera, vanno aggiunte le seguenti cose:
SA
- configurazione di sistema: va messo il nuovo endpoint nel backend e va segnato l'utilizzo che ne fa il frontend
- architettura delle componenti: va tolto l'interceptor e vanno messe le dipendenze nuove alle guardie (frontend), va messo il nuovo endpoint (backend)
- dettaglio: le modifiche di conseguenza all'architettura
PdQ
- definizione dei test di unità + tracciamento
- definizione dei test di sistema + tracciamento
Codice
- implementazione della specifica
- implementazione dei test

**Comment by albertolazari** [comment]
Questo in realtà è risolto, o comunque ce ne freghiamo?

**Comment by SkiFire13** [comment]
Già sistemato in #106, ci siamo solo dimenticato di chiuderlo.
